name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Elastic Beanstalk
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-southeast-2
      EB_ENV: flower-shop-api-env
      EB_APP: flower-shop-api
      EB_PLATFORM: "Ruby"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Elastic Beanstalk CLI
        run: |
          pip install --upgrade awsebcli
          eb --version

      - name: Initialize Elastic Beanstalk (if not already set up)
        working-directory: flower-shop-api
        run: |
          if ! eb status $EB_ENV 2>/dev/null; then
            eb init -p "$EB_PLATFORM" $EB_APP --region $AWS_REGION  
            eb use $EB_ENV
          fi

      - name: Create env.config for Elastic Beanstalk
        run: |
          mkdir -p .ebextensions
          echo "option_settings:" > .ebextensions/env.config
          echo "  aws:elasticbeanstalk:application:environment:" >> .ebextensions/env.config
          echo "    SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}" >> .ebextensions/env.config

      - name: Deploy to Elastic Beanstalk
        working-directory: flower-shop-api
        env:
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        run: |
          eb deploy $EB_ENV
