name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Elastic Beanstalk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Set Environment Variables in Elastic Beanstalk
        working-directory: flower-shop-api
        run: |
          eb setenv SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}

      - name: Install Elastic Beanstalk CLI
        run: |
          pip install --upgrade awsebcli
          eb --version

      - name: Initialize Elastic Beanstalk (if not already set up)
        working-directory: flower-shop-api
        run: |
          if ! eb status 2>/dev/null; then
            eb init -p "Ruby" flower-shop-api --region ap-southeast-2  
          fi

      - name: Deploy to Elastic Beanstalk
        working-directory: flower-shop-api
        run: |
          eb deploy
